---
###############################################################
#                   Authelia configuration                    #
###############################################################

server:
  address: 'tcp://:9091'

log:
  level: 'debug'

totp:
  issuer: 'wtsdr.com'

identity_validation:
  reset_password:
    jwt_secret: ${AUTHELIA_JWT_SECRET}

authentication_backend:
  file:
    path: '/config/users_database.yaml'

access_control:
  default_policy: 'deny'
  rules:
    - domain: 'public.wtsdr.com'
      policy: 'bypass'
    - domain: 'traefik.wtsdr.com'
      policy: 'one_factor'
    - domain: 'secure.wtsdr.com'
      policy: 'two_factor'

session:
  secret: ${AUTHELIA_SESSION_SECRET}

  cookies:
    - name: 'authelia_session'
      domain: 'wtsdr.com'  # Should match whatever your root protected domain is
      authelia_url: 'https://authelia.wtsdr.com'
      expiration: '1 hour'  # 1 hour
      inactivity: '5 minutes'  # 5 minutes
      default_redirection_url: 'https://public.wtsdr.com'

regulation:
  max_retries: 3
  find_time: '2 minutes'
  ban_time: '5 minutes'

storage:
  postgres:
    address: tcp://postgres:5432 # PostgreSQL server address
    database: wtsdr # Database name
    username: ${POSTGRES_USER} # Username for database access
    password: ${POSTGRES_PASSWORD} # Password for the user
    schema: auth # Schema name (default is public)
  encryption_key: ${AUTHELIA_STORAGE_ENCRYPTION_KEY}

notifier:
  filesystem:
    filename: '/config/notification.txt'
...