###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

# List of users
users:
  admin:
    disabled: false
    displayname: 'Administrator'
    # Password hash for the admin user. Set via environment with AUTHELIA_USERS_FILE_PASSWORD_HASH or update at runtime.
    # For local dev, Authelia supports plain text only if 'password' key is used, but recommended to use a hash.
    password: ${AUTHELIA_ADMIN_PASSWORD:-password}
    email: 'admin@wtsdr.com'
    groups:
      - 'admins'
      - 'dev'
