# The following is Casdoor demo site config, replace them with your own Casdoor config

endpoint = "https://door.casdoor.com"
client_id = "3da4c64cf2d349f0b11c"
client_secret = "f06b5389863413ee75e54b0a8867ad315ba2733a"
certificate = """-----BEGIN CERTIFICATE-----
MIIE2TCCAsGgAwIBAgIDAeJAMA0GCSqGSIb3DQEBCwUAMCYxDjAMBgNVBAoTBWFk
bWluMRQwEgYDVQQDDAtjZXJ0XzU1OG4zeTAeFw0yNTA5MTYwMzE1MzBaFw00NTA5
MTYwMzE1MzBaMCYxDjAMBgNVBAoTBWFkbWluMRQwEgYDVQQDDAtjZXJ0XzU1OG4z
eTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAMVO3/baYdMOzFM8fOC6
jTsHAuR0rrepG+Y8t3uNJfVXojv0pUMCwlvn/9WukPOzaM4iFftfjkaXJXg4TVmo
fv3aqIN6dow2s1rrLAeGeVIkgjxzVYsUIB0pH3b94uwVQQ0/cKFERFhUcaV3lsog
xmiBLwsjMvyer6fGmEuNITywYFdbvBDqQU/TXEWfZWuDU81I2ISdwuWv+UDRXHxA
x3lbhVxStR9xiYLqtheK+0YKK2JRtOup4FjQjOLEzMFiYigy9ipsHbnCLzE7vFc/
SUWCrFFhGBSQkcwtYeA3IgTJ8Mcjuvlv8hFzzkEhy67Kd77Co1h0xLRTGazF/G5q
h2GK0hImReLRpGNwDgqz9NLHQ3Hg2nq4uK8UrjwMCwk+qX4fcJwO3Aqi3WbaF/F3
fYDF4dmJPbaUMtnXVqwyCyflnzbViSMjUXEPNwASB1xoeKVfHcePIYJPTJ/KFvHv
SUVIeQEXFLtQmHsp4dQdKKbj39xjcpgv0qqfj/QGbU999+AW02xrrQE6KqfAgGol
O6HBClTriIrQ2UO9wxrinyxiDBnJ6Ppb2rV+BeIQOsR+RnhL5p4fAN3g/ezga9dw
KRImuAkRmALoGmvmsfrF2oZc2RWxFcDxOPhWyECia+C14QxpoKiR5EhyAR9Jf6xI
SErC2QliTp/w/47zbU9sFWTvAgMBAAGjEDAOMAwGA1UdEwEB/wQCMAAwDQYJKoZI
hvcNAQELBQADggIBAKoZ0M2etlRuqNJpzrt5cKQz6FFYl5KC2LxEa0zpLo7oAokz
9E5X2ogvIrNmjN9fX3qMrJxGFFYSFlRJKKT3XRmmk/b5D0V2GDVxgFJOtsGGmVfk
cbuQsr5Mfi/v1pYf9pMh60AhtK/bpDYHr0qX8PrvhPVguOApOt2sbtmUU2KdIdMV
h3KRKKcPNV1evlWS/KsiSA6augJz1FKJO5GiNdM9LFncp3NjqrS9DaVnv7Bf1A+9
oYG2BEieNkc73uZ+L2No8eL+kkGNWk/kUvlsSzqK54R+LZr9WGpVr0PGPBwEJQMC
u2D5Re1/Ih223cW4jN80HX1QRCAOEUuTBul7ppgGbExUVtzY93RWb8BjMcQLJRBt
gzD56L0uDg4cV1zvdkIqSsikdnypOn2DUuywnBix3H4t9gdp+h0/EfD9kUq2gABC
Wnpmw+sgavL+mBXV9mdcqVzY+cJ1RB5Xx6r3/6LAqAlx+UM7t+kcjsZlinVI5oE1
98+CVEEyqlUQFMzaY4zHgbrSP2P27L6sDIt4sopAcq3OpAJ+pAP8wm31JOGHw3Dp
/Y9v0Z5g/26aj+zo3a3na6mAnxUYrGW83Y+mNg/OceDFTDB8mINHao/i+BiRZrTr
k642vPno9ZLYTx3uIDNlt5pE3LNRt+g/rv/IKBA8Kwt5dkB0cuZnHSKTbRkB
-----END CERTIFICATE-----"""
org_name = "wtsdr"
