global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'postgres'
    static_configs:
      - targets: [ 'postgres-exporter:9187' ]
  - job_name: 'authelia'
    static_configs:
      - targets: ['authelia:8080']
